baseURL = "https://mohsenabdolahi.ir/"
languageCode = "en-us"
title = "Mohsen Abdolahi"
theme = "terminal"
paginate = 5
enableGitInfo = true   # ✅ already enabled, good for "last updated" dates

# Required for Chroma and the custom syntax highlighting
[markup]
  [markup.highlight]
    noClasses = false
    style = "github-dark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Security and HTTPS settings
[security]
  [security.funcs]
    getenv = ["^HUGO_", "^CI$"]
  [security.exec]
    allow = ["^(dart-)?sass(-embedded)?$", "^go$", "^npx$", "^postcss$"]

# Deployment settings
[deployment]
  [[deployment.targets]]
    name = "production"
    URL = "s3://your-bucket?region=us-east-1"
  [[deployment.matchers]]
    pattern = "^.+\\.(js|css|svg|ttf)$"
    cacheControl = "max-age=31536000, no-transform, public"
    gzip = true
  [[deployment.matchers]]
    pattern = "^.+\\.(png|jpg)$"
    cacheControl = "max-age=31536000, no-transform, public"
    gzip = false

[params]
  # dir name of your main content (default is `content/posts`)
  contentTypeName = "posts"

  # how many menu items to show in header
  showMenuItems = 4

  # layout options
  showLanguageSelector = false
  fullWidthTheme = false
  centerTheme = true

  # images & content
  autoCover = true
  showLastUpdated = true
  readingTime = true
  Toc = true
  TocTitle = "Table of Contents"

  # custom accent color
  themeColor = "orange"

[params.twitter]
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "" # this should not be set

    [languages.en.params]
      subtitle = "Software Engineer - Backend Developer"
      owner = "Mohsen Abdolahi"
      keywords = "software engineer, backend developer, c#, golang, .net, web development, programming, game development"
      copyright = "© 2025 Mohsen Abdolahi"
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "~ Mohsen Abdolahi ~"
        logoHomeLink = "/"

      # Menu items
      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "#about"
        [[languages.en.menu.main]]
          identifier = "experience"
          name = "Experience"
          url = "#experience"
        [[languages.en.menu.main]]
          identifier = "skills"
          name = "Skills"
          url = "#skills"
        [[languages.en.menu.main]]
          identifier = "contact"
          name = "Contact"
          url = "#contact"

# Social links and contact info
[params.social]
  github = "MsN-12"
  linkedin = "mohsen-abdolahi"
  email = "mohsen12abdolahi@gmail.com"
  phone = "+98 9390433026"
  location = "Iran, Fars"

# RSS configuration
[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
